LinReg:
  model: LinearRegression
  model_params: {}

XGBoost_OF:
  model: XGBoost
  model_params:
    n_estimators: 1000
    max_depth: 14
    learning_rate: 0.3
    subsample: 1.0
    min_child_weight: 1
    colsample_bytree: 1.0
    colsample_bylevel: 1.0
    lambda: 0
    alpha: 0

XGBoost_OT:
  model: XGBoost
  model_params: to_tune

GAM_OF:
  model: GAM
  model_params:
    n_bases: 50
    lam: 0.000001

GAM_OT:
  model: GAM
  model_params: to_tune

SVM_OF:
  model: SVM-RBF
  model_params:
    C: 1000
    gamma: 15

SVM_OT:
  model: SVM-RBF
  model_params: to_tune
